sony/nnabla-examples

cifar10-100-collection/classification.py, distributed/cifar10-100/args.py, distributed/cifar10-100/cifar100_data.py, distributed/cifar10-100/cifar10_data.py, distributed/cifar10-100/multi_device_multi_process_classification.py
We add `all_reduce(ndarray, ...)` interface. With this feature, one can do
- the distributed validation over multiple nodes
- the data parallel distributed training with dynamic neural network
=> 20171212 distributed validation

mnist-collection/README.md, mnist-collection/vae.py
=> added vae example

GANs/pggan/README.md, GANs/pggan/args.py, GANs/pggan/datasets.py, GANs/pggan/functions.py, GANs/pggan/generate.py, GANs/pggan/helpers.py, GANs/pggan/ms_ssim.py, GANs/pggan/networks.py, GANs/pggan/sliced_wasserstein.py, GANs/pggan/train.py, GANs/pggan/trainer.py, GANs/pggan/validate.py
An example of the Progressive Growing of GANs are now available.
=> Example of the Progressive Growing of GANs.

capsule_net/README.md, capsule_net/reconstruct_tweaked_capsules.py, capsule_net/train.py, cifar10-100-collection/classification.py, imagenet-classification/create_cache_file.py, mnist-collection/README.md, mnist-collection/args.py, mnist-collection/vat.py, penn-treebank/README.md, penn-treebank/args.py, word-embedding/README.md, word-embedding/word_embedding.py
Update documentation replacing cuda.cudnn --> cudnn.
=> [doc] fix cuda.cudnn --> cudnn and update document.

imagenet-classification/README.md, imagenet-classification/args.py, imagenet-classification/multi_device_multi_process_classification.py
=> add multi gpu.

imagenet-classification/README.md, imagenet-classification/multi_device_multi_process_classification.py
=> fixed doc of multi gpu imagenet.

capsule_net/README.md, capsule_net/model.py, cifar10-100-collection/args.py, distributed/cifar10-100/args.py, mnist-collection/args.py, mnist-collection/vat.py, object-detection/yolov2/yolov2_nnp.py, reduction/cifar10/distillation/README.ipynb, reduction/cifar10/distillation/args.py, reduction/cifar10/quantization/args.py, reduction/cifar10/resnet2rnn/args.py, reduction/cifar10/structured-sparsity/args.py, word-embedding/word_embedding.py
=> document fix

imagenet-classification/README.md, imagenet-classification/args.py, imagenet-classification/classification.py, imagenet-classification/multi_device_multi_process_classification.py
=> bug fix of ImageNet example.

imagenet-classification/README.md
=> fix typo in README.md

imagenet-classification/multi_device_multi_process_classification.py, imagenet-classification/requirements.txt
modified version of nnabla.
use rng with input valule of slice function.
=> [imagenet] Use DataIterator.slice for training data

GANs/pggan/trainer.py
Investigation of `clear_all_graph_links` causing something bad is another issue.
=> Delete clear all graph links.

mnist-collection/dcgan.py
Originally indicated by; https://github.com/sony/nnabla-examples/issues/62
=> minor fix in dcgan example

imagenet-classification/classification.py, imagenet-classification/multi_device_multi_process_classification.py
Please check this modification.
=> delete a special process of data reading

imagenet-classification/classification.py, imagenet-classification/multi_device_multi_process_classification.py
=> modified accumulate_error.

imagenet-classification/README.md, imagenet-classification/model_inference.py
Please check this inference code.
=> Add an inference script in ImageNet training example

imagenet-classification/README.md
Please check this modification.
=> modified a command of inference.

semantic-segmentation/deeplabv3plus/eval.py, semantic-segmentation/deeplabv3plus/image_preprocess.py, semantic-segmentation/deeplabv3plus/model.py, semantic-segmentation/deeplabv3plus/model_inference.py, semantic-segmentation/deeplabv3plus/segmentation_data.py, semantic-segmentation/deeplabv3plus/train.py
=> Enabled non square input size in DeepLabV3+ example

GANs/pix2pix/README.md, GANs/pix2pix/generator.py, GANs/pix2pix/pix2pix.py
format
temp
reflect review and format
=> [Fix] Pix2Pix for Large Batch Size

GANs/sagan/models.py, cifar10-100-collection/models.py, distributed/cifar10-100/models.py
=> Fix python3 division.

semantic-segmentation/deeplabv3plus/args.py
=> DeepLabV3+: Fix default image size arguments

GANs/instagan/datasets/generate_ccp_dataset.py
=> added formated code

GANs/stargan/README.md, GANs/stargan/args.py, GANs/stargan/model.py, GANs/stargan/train.py
Add a link to pretrained weights for StarGAN. The model is trained on celebA dataset, with 5 attributes.
=> add pretrained models to StarGAN

meta-learning/README.md, meta-learning/data_generator_maml.py, meta-learning/net.py, meta-learning/train_maml.py
Added Model Agnostic Meta-Learning (MAML) implementation and its example.
=> Added MAML

capsule_net/_checkpoint_nnp_util.py, capsule_net/train.py, utils/README.md, utils/checkpoint_util.py, utils/save_nnp.py
Add 2 utility functions experimentally.
+ save_nnp function which saves the `nnp` files before and after the training so that one can use the pretrained model.
+ checkpoint functions. One can save the checkpoint files which contains the parameters and its state information. By using this, one can resume the training from the certain point of training.
=> Add save_nnp and checkpoint script.

imagenet-classification/_checkpoint_nnp_util.py, imagenet-classification/args.py, imagenet-classification/classification.py
checkpoint/resume and save_nnp for imagenet example.
=> checkpoint and nnp for imagenet

semantic-segmentation/deeplabv3plus/_checkpoint_nnp_util.py, semantic-segmentation/deeplabv3plus/args.py, semantic-segmentation/deeplabv3plus/train.py
checkpoint/resume and save_nnp for DeepLabv3 example.
=> nnp checkpoint in deeplabv3plus

cifar10-100-collection/_checkpoint_nnp_util.py, cifar10-100-collection/args.py, cifar10-100-collection/classification.py
Add checkpoint / nnp save function to CIFAR10/100 examples.
=> save nnp checkpoint for cifar10/100

mnist-collection/_checkpoint_nnp_util.py, mnist-collection/args.py, mnist-collection/classification.py, mnist-collection/classification_bnn.py, mnist-collection/dcgan.py, mnist-collection/siamese.py, mnist-collection/vae.py, mnist-collection/vat.py
Add checkpoint / nnp save function to MNIST examples.
=> save nnp checkpoint for mnist

speech-synthesis/WaveNet/_checkpoint_nnp_util.py, speech-synthesis/WaveNet/args.py, speech-synthesis/WaveNet/train.py
Add checkpoint / nnp save function to WaveNet examples.
=> save nnp and checkpoint for speech synthesis

penn-treebank/_checkpoint_util.py, penn-treebank/args.py, penn-treebank/train.py
Add checkpoint / nnp save function to pentreebank examples.
=> save nnp checkpoint for penn tree bank

GANs/esrgan/authors-scripts/extract_subimgs_single.py, GANs/esrgan/train_esrgan.py, GANs/esrgan/train_psnr_rrdb.py
Fix minor issues in ESRGAN training example.
=> [ESRGAN] minor fixes

Dockerfile, imagenet-classification/README.md
Supplemental updates related to #135.
=> Update reamdme and Dockerfile to support dali 0.18.0

meta-learning/_checkpoint_nnp_util.py, meta-learning/prototypical/prototypical.py
Add nnp / checkpoint saving functions to metalearning  examples.
=> add saving nnp/checkpoint functions to metalearning

meta-learning/README.md, meta-learning/data/celeb_a_data.py, meta-learning/prototypical/_checkpoint_nnp_util.py, meta-learning/prototypical/prototypical.py
modified prototypical net examples for fewshot face identification with CelebA dataset
=> modified prototypical net examples for fewshot face identification 

utils/neu/comm.py, utils/neu/misc.py
Fixes the following;
* Fix AttrDict parent
* CommunicatorWrapper float context
=> Fix ImageNet classification training example due to merge conflict

LICENSE, utils/README.md, utils/neu/metrics/README.md, utils/neu/metrics/__init__.py, utils/neu/metrics/gan_eval/README.md, utils/neu/metrics/gan_eval/__init__.py, utils/neu/metrics/gan_eval/fid.py, utils/neu/metrics/gan_eval/im2ndarray.py, utils/neu/metrics/gan_eval/inception_score.py, utils/neu/metrics/gan_eval/inceptionv3.py, utils/neu/metrics/lpips/README.md, utils/neu/metrics/lpips/__init__.py, utils/neu/metrics/lpips/compute.py, utils/neu/metrics/lpips/lpips.py
Add DL-based evaluation metrics mainly used in GAN.
* LPIPS
* Inception Score
* Fréchet Inception Distance
Each metric is provided with CLI.
=> add LPIPS, Inception Score and FID.

README.md, interactive-demos/esrgan.ipynb, interactive-demos/fan.ipynb, interactive-demos/sagan.ipynb
Add Colab interactive inference demos for ESR-GAN, SAGAN, FAN
=> Add Colab Inference Demos for ESR-GAN, Self-Attention GAN, FAN

interactive-demos/esrgan.ipynb, interactive-demos/fan.ipynb, interactive-demos/imagenet_classification.ipynb, interactive-demos/psmnet.ipynb, interactive-demos/sagan.ipynb, interactive-demos/stargan.ipynb, interactive-demos/yolov2.ipynb
Set Default Runtime for Colab Demos as GPU
=> Set Default Runtime for Colab as GPU

distributed/cifar10-100/multi_device_multi_process_classification.py
Fix simultaneous access to the same data file, and prevent writing the same data from different computation nodes.
=> Fixed issue that multiple processes access the same file on multinode training

GANs/tecogan/README.md
fix url link for vgg19's pretrained weights.
=> fix pretrained weights download link

interactive-demos/stylegan2.ipynb
Uncomment the clone and cd lines.
=> stylegan2 demo: uncomment lines

GANs/reenactgan/preprocess.py
Removed unused class and fixed typo.
=> fix import issue

GANs/stylegan2/generate.py, GANs/stylegan2/networks.py, interactive-demos/stylegan2.ipynb
currently Colab demo for StyleGAN2 is not working, so fixed it. Arranged the demo as well.
=> fix relative imports issue

imagenet-classification/data.py
support the latest version of dali to suppress DeprecationWarning in imagenet-classification
=> dali latest version

Dockerfile
remove conda to use from dockerfile.
=> remove conda from dockerfile

responsible_ai/data_cleansing/datasets/create_cifar10_csv.py, responsible_ai/data_cleansing/datasets/create_mnist_csv.py, responsible_ai/data_cleansing/datasets/create_stl10_csv.py, responsible_ai/data_cleansing/datasets/utils.py, responsible_ai/data_cleansing/sgd_influence/analyze.py, responsible_ai/data_cleansing/sgd_influence/dataset.py, responsible_ai/data_cleansing/sgd_influence/eval.py, responsible_ai/data_cleansing/sgd_influence/infl.py, responsible_ai/data_cleansing/sgd_influence/model.py, responsible_ai/data_cleansing/sgd_influence/train.py, responsible_ai/data_cleansing/sgd_influence/utils.py, responsible_ai/data_cleansing/train_infl_eval.py
The format of these codes was checked and changed.
=> Format changed

GANs/pix2pix/facade.py
Simply use urllib for http access instead of requests.
=> Use urllib instead of requests

responsible_ai/face_evaluation/face_evaluation.py
This is python file part of a colab interactive demo of facial evaluation for skin colors by using Individual Typology Angle (ITA). We need to release this python part firstly in advance of colab part so that we can test the interactive demo on the colab.
=> Facial evaluation for skin colors (python part) 

Dockerfile, imagenet-classification/reference_weight_converter/Dockerfile.caffe-senet, shape-reconstruction/implicit-geometric-regularization/docker/Dockerfile
- PIP_INS_OPTS
- CURL_OPTS
- WGET_OPTS
- YUM_OPTS
- APT_OPTS
- PYTHONWARNINGS
=> Allow additional options to commands that use network

GANs/tecogan/generate.py
=> Add clear buffer in forward pass in TecoGAN

GANs/tecogan/generate.py
TecoGAN doesn't follow our auto format rules, so correct it.
=> Fix example code to conform to the auto-format rules

responsible_ai/gender_bias_mitigation/utils.py
This PR fixes the auto-format issue for responsible AI's gender_bias_mitigation.
=> Fix auto format

responsible_ai/README.md
This is an update of README of responsible_ai to include influence functions.
=> [XAI] Update responsible_ai README

GANs/stargan/args.py, NAS/ENAS/README.md, meta-learning/prototypical/prototypical.py
This commit is to fix errors in nnabla examples
=> fix errors in nnabla examples

3d-object-classification/pointnet/README.md, 3d-object-classification/pointnet/data/__init__.py, 3d-object-classification/pointnet/data/data_utils.py, 3d-object-classification/pointnet/data/download_data.sh, 3d-object-classification/pointnet/data/modelnet40_normal_resampled_dataiter.py, 3d-object-classification/pointnet/evaluate.py, 3d-object-classification/pointnet/loss.py, 3d-object-classification/pointnet/model.py, 3d-object-classification/pointnet/model_utils.py, 3d-object-classification/pointnet/requirements.txt, 3d-object-classification/pointnet/running_utils.py, 3d-object-classification/pointnet/train.py
Added a nnabla version of [pointnet](https://arxiv.org/abs/1612.00593) for the 3d object classification.
This implementation was tested by the [modelnet_40 dataset](https://modelnet.cs.princeton.edu/)
=> Pointnet for 3d object classification implementation

interactive-demos/file_format_converter.ipynb
add demonstration for file format converter introduction.
=> add file_format_converter.ipynb

GANs/stylegan2-cdc/execution/evaluate.py, GANs/stylegan2-cdc/execution/ops.py, GANs/stylegan2-cdc/execution/train.py, GANs/stylegan2-cdc/models/__init__.py, GANs/stylegan2-cdc/models/discriminators.py, GANs/stylegan2-cdc/models/generators.py, GANs/stylegan2-cdc/models/networks.py, GANs/stylegan2-cdc/models/ops.py, GANs/stylegan2-cdc/models/patch_discriminators.py, GANs/stylegan2-ewc/execution/evaluate.py, GANs/stylegan2-ewc/execution/ops.py, GANs/stylegan2-ewc/execution/train.py, GANs/stylegan2-ewc/models/networks.py, GANs/tecogan/generate.py, responsible_ai/rejection_option_based_classification/utils.py, shape-reconstruction/implicit-differentiable-renderer/helper.py, shape-reconstruction/implicit-differentiable-renderer/ray_tracer.py, shape-reconstruction/implicit-differentiable-renderer/synthesize.py
Update auto-format for latest nnabla-examples
=> format for latest nnabla-examples

GANs/slegan/README.md, GANs/slegan/generator.py, GANs/slegan/interpolate.py, GANs/slegan/loss.py, GANs/slegan/lpips.py, GANs/slegan/stylemix.py
Modified loss function with lpips and added scripts for interpolation and style mixing.
=> Modified loss function with lpips and added scripts for interpolation and style mixing

Dockerfile, imagenet-classification/README.md, imagenet-classification/args.py, imagenet-classification/cfg/finetune10.yaml, imagenet-classification/create_caltech101_dataset.py, imagenet-classification/train.py
Added finetuning sample demonstrated on Caltech101 dataset.
=> ImageNet classification finetuning sample

vision-and-language/clip/README.md, vision-and-language/clip/notebook-examples/convert_weights.ipynb
@TE-andrewshin 
minor update for CLIP branch(#251):
- update README to mention that the work was done during the internship
- add conversion code
=> WIP: Feature/20210921 clip inference

interactive-demos/gradcam.ipynb
This is a change to GPU version from CPU version on Grad-CAM colab interactive demo.
=> [XAI] Grad-CAM colab with GPU

image-classification/imagenet/README.md, image-classification/imagenet/_checkpoint_nnp_util.py, image-classification/imagenet/obsolete/_checkpoint_nnp_util.py, image-generation/stylegan2-cdc/execution/CrossDomainCorrespondence/VisitUtils.py, image-translation/stylegan2-distillation/data_generation.py, image-translation/stylegan2-distillation/generate_attribute_direction.py
Fix path issue for `image-classification/imagenet` and `image-translation/stylegan2-distillation`.
Also, add missing code for `image-generation/stylegan2-cdc`.
=> fix error of import path in nnabla-example

utils/README.md
Fix broken link in neu document
=> Fix broken link in neu document

interactive-demos/adversarial_debiasing_images.ipynb
This is a colab interactive demo of adversarial debiasing for Images.
=> [Fairness] Adversarial Debiasing for Images (Part-2) first commit

vision-and-language/clip/README.md, vision-and-language/clip/args.py, vision-and-language/clip/clip/clip.py, vision-and-language/clip/clip/model.py, vision-and-language/clip/datasets.py, vision-and-language/clip/losses.py, vision-and-language/clip/main.py, vision-and-language/clip/scheduler.py, vision-and-language/clip/train.py, vision-and-language/clip/weight_convert_nn2pth.py
This PR is for adding the training scripts of CLIP.
=> Add CLIP training

responsible_ai/prejudice_remover_regularizer/utils.py
Patch to auto-format ci failure.
=> Fix auto-format failure

image-superresolution/esrgan/convert_vgg19_weights.py, object-detection/centernet/src/lib/utils/voc_eval_lib/datasets/pascal_voc.py, object-detection/yolov2/image.py, object-detection/yolov2/image2.py, object-detection/yolov2/utils.py, object-detection/yolov2/valid.py, semantic-segmentation/deeplabv3plus/convert_tf_nnabla.py, semantic-segmentation/deeplabv3plus/xception_65.py, video-colorization/deep-exemplar-based-video-colorization/preprocess.py, video-superresolution/tecogan/authors_scripts/dataPrepare.py, video-superresolution/tecogan/authors_scripts/download_test_data.py
new autopep8 has been release, and it supports E275.
This PR will modify our code to support E275.
=> modify nnabla-examples code format to support new autopep8

diffusion-models/config.py, diffusion-models/diffusion.py, diffusion-models/generate.py, diffusion-models/model.py
Added ODE based samplers (PLMS and DPM-Solver-2)
=> Add ODE based samplers

interactive-demos/fomm.ipynb
Somehow it raises an error due to the lack of `imageio-ffmpeg`, modified the cell to install that before inference.
=> add ffmpeg installation

.gitignore, diffusion-models/.gitignore, diffusion-models/conf/dataset/laion400m.yaml, diffusion-models/conf/model/adm_64_class_cond.yaml, diffusion-models/conf/model/adm_64to256_class_cond.yaml, diffusion-models/conf/model/efficient_unet_64to256.yaml, diffusion-models/conf/model/efficient_unet_64to256_class_cond.yaml, diffusion-models/conf/model/imagen_64.yaml, diffusion-models/conf/runtime/default.yaml, diffusion-models/conf/train/imagenet_64to256_efficient_unet.yaml, diffusion-models/conf/train/laion400m_64_imagen.yaml, diffusion-models/config.py, diffusion-models/dataset/__init__.py, diffusion-models/dataset/cifar10.py, diffusion-models/dataset/common.py, diffusion-models/dataset/imagenet.py, diffusion-models/dataset/laion.py, diffusion-models/dataset/preprocess/README.md, diffusion-models/dataset/preprocess/augment_laion_wds_t5_embed.py, diffusion-models/dataset/preprocess/create_valid_tar_lists.py, diffusion-models/dataset/preprocess/requirements.txt, diffusion-models/diffusion.py, diffusion-models/generate.py, diffusion-models/layers.py, diffusion-models/model.py, diffusion-models/requirements.txt, diffusion-models/sdedit.py, diffusion-models/train.py, diffusion-models/unet.py, diffusion-models/utils.py
This PR includes following items to support [Photorealistic Text-to-Image Diffusion Models with Deep Language Understanding (AKA Imagen)](https://arxiv.org/abs/2205.11487).
- text conditional training with LAION dataset
- Inference with Classifier-Free Guidance 
- text embedding and cross attention
- Efficient UNet 
- Gaussian Conditioning Augmentation for robust upsampler
- numerical stability improvement
=> Text conditional DPM

frame-interpolation/zooming-slow-mo/authors_scripts/create_lmdb.py, frame-interpolation/zooming-slow-mo/authors_scripts/generate_lr.py, stereo-depth/PSMnet/finetune.py, video-superresolution/jsigan/inference.py
This PR fixes fomatting errors caused by autopep8 v2.0.0 which has been recently released on Oct 29.
=> Update formatting by autopep8>=2

image-generation/slegan/args.py, image-generation/slegan/generate.py, image-generation/slegan/train.py
This PR allows training to be resumed from latest checkpoint file.
Related Issue is: https://github.com/sony/nnabla-examples/issues/289
=> Enable training from checkpoint for SLE-GAN

vision-and-language/clip/README.md, vision-and-language/clip/clip/model.py
This PR is for fixing links to CLIP weights.
=> fix links of CLIP weights

object-detection/centernet/src/lib/opts.py, object-detection/centernet/src/lib/trains/ctdet.py, object-detection/centernet/src/main.py
Add patch to nnabla-examples to fix check format issue.
=> fix nnabla-examples format

object-detection/centernet/README.md, object-detection/centernet/src/demo.py, object-detection/centernet/src/lib/detectors/base_detector.py, object-detection/centernet/src/lib/detectors/ctdet.py, object-detection/centernet/src/lib/models/networks/centernet_dlav0.py, object-detection/centernet/src/lib/models/networks/centernet_resnet.py, object-detection/centernet/src/lib/opts.py, object-detection/centernet/src/lib/trains/ctdet.py, object-detection/centernet/src/lib/utils/debugger.py, object-detection/centernet/src/main.py, object-detection/centernet/src/save_graph.py, object-detection/centernet/src/save_nnp.py, object-detection/centernet/src/test.py
* Move the loss monitor and loss function inside the Trainer class for encapsulation.
* Improve args
* Rename --checkpoint to --trained_model_path
* Rename --checkpoint_dir to --trained_model_dir
* Fix minor bugs(wrong weight name, duplicate conditional statement) of test.py
=> Improve CenterNet

image-generation/sagan/models.py, image-superresolution/esrgan/vgg19.py, image-translation/instagan/dataloader.py, image-translation/instagan/models.py, image-translation/instagan/train.py, image-translation/munit/datasets.py, image-translation/munit/models.py, image-translation/stargan/generate.py, neural-architecture-search/ENAS/macro_CNN.py, object-detection/centernet/src/lib/trains/ctdet.py, object-detection/centernet/src/lib/utils/voc_eval_lib/model/test.py, object-detection/centernet/src/main.py, reinforcement_learning/dqn_reference_implementation/validator.py, responsible_ai/gan_data_debiased/utils/utils.py, semantic-segmentation/deeplabv3plus/dataset_utils.py, semantic-segmentation/deeplabv3plus/model_inference.py, semantic-segmentation/deeplabv3plus/plot_accuracy.py, semantic-segmentation/deeplabv3plus/segmentation_data.py, shape-reconstruction/implicit-differentiable-renderer/extract.py, shape-reconstruction/implicit-differentiable-renderer/network.py, shape-reconstruction/implicit-differentiable-renderer/ray_tracer.py, utils/neu/metrics/gan_eval/fid.py, video-colorization/deep-exemplar-based-video-colorization/preprocess.py, video-superresolution/jsigan/generate_lr_hdr.py, video-superresolution/jsigan/inference.py, video-superresolution/tecogan/authors_scripts/data/tst_scene_render.py, video-superresolution/tecogan/vgg19.py
Due to autopep8 2.0.1 update, auto-format needs to be updated correspondingly.
=> update nnabla-examples format

responsible_ai/massage_data/utils.py, responsible_ai/utils/data_loader.py, responsible_ai/utils/data_process.py
Updated 'utils.py' file for Massage data algorithm
Included preprocess class that can be used for data preprocessing for model training and fairness evaluation
Preprocessor class supported 5 datasets :
- Adult Census Income Dataset
- German Credit Dataset
- ProPublica COMPAS Dataset
- Bank Marketing Dataset
- Law school GPA dataset
=> [Fairness] Included data pre-processor class

interactive-demos/massage_data.ipynb, interactive-demos/preferential_sampling.ipynb
Refactor Code:
- Fixed absolute image path in Preferential Sampling notebook
- Uncommented preparation setup in Massage Data notebook
=> [Fairness] Refactor code

Dockerfile, object-detection/yolov2/ros/nnabla_object_detection/src/detection_node.cpp, shape-reconstruction/implicit-differentiable-renderer/Dockerfile
Upgrade docker base from ubuntu18 to ubuntu20.
This is related to https://github.com/sony/nnabla/pull/1208
=> upgrade docker base ubuntu2004

image-classification/cifar10-100/classification.py, image-translation/spade/models.py, utils/neu/save_nnp.py
Details could be referred to https://github.com/sony/nnabla/pull/1215.
=> pycodestyle update auto format

diffusion-models/train_pixel_classifier.py
Fix auto-format issue due to latest autopep8 upgrade.
=> Update auto format
